### ISSUE TITLE
graphics issue on db410c-Inconsistent behaviour of graphics on db410c with mir-kiosk snap

### ISSUE THREAD

**Issue by laxman456** [MirServer/mir-kiosk#1]
During the first boot after installing mir-kiosk snap when i tried with "snap set mir-kiosk-apps app=rssnews"
nothing got displayed on display.If i reboot then rssnews feed did come up on display.
This behaviour is insconsistent as i do multiple reboots and with different mir-kiosk-apps

syslog of first boot:
Sep  1 04:41:27 localhost snap[3059]: /snap/mir-kiosk-apps/15/bin/mir-kiosk-app-daemon: line 98: kill: (3073) - No such process
Sep  1 04:41:27 localhost snap[3059]: rssnews was already dead!
Sep  1 04:41:27 localhost systemd[1]: snap.mir-kiosk-apps.mir-kiosk-app-daemon.service: Main process exited, code=exited, status=1/FAILURE
Sep  1 04:41:27 localhost systemd[1]: snap.mir-kiosk-apps.mir-kiosk-app-daemon.service: Unit entered failed state.
Sep  1 04:41:27 localhost systemd[1]: snap.mir-kiosk-apps.mir-kiosk-app-daemon.service: Failed with result 'exit-code'.
Sep  1 04:41:27 localhost systemd[1]: snap.mir-kiosk-apps.mir-kiosk-app-daemon.service: Service hold-off time over, scheduling restart.
Sep  1 04:41:27 localhost systemd[1]: Stopped Service for snap application mir-kiosk-apps.mir-kiosk-app-daemon.
Sep  1 04:41:27 localhost systemd[1]: snap.mir-kiosk-apps.mir-kiosk-app-daemon.service: Start request repeated too quickly.
Sep  1 04:41:27 localhost systemd[1]: Failed to start Service for snap application mir-kiosk-apps.mir-kiosk-app-daemon.
Sep  1 04:41:43 localhost rsyslogd-2007: action 'action 10' suspended, next retry is Fri Sep  1 04:42:13 2017 [v8.16.0 try http://www.rsyslog.com/e/2007 ] 

after reboot rssnews feed come up and i tried to change to different mir-kisok-apps
syslog after reboot:
Sep  1 04:43:49 localhost kernel: [   45.707051] audit: type=1400 audit(1504241029.204:41): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6" pid=1530 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:54 localhost kernel: [   50.696421] audit: type=1400 audit(1504241034.192:42): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6-0" pid=1532 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:54 localhost rsyslogd-2007: action 'action 10' suspended, next retry is Fri Sep  1 04:44:24 2017 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
Sep  1 04:43:54 localhost kernel: [   50.715467] audit: type=1400 audit(1504241034.212:43): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6-0" pid=1533 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:54 localhost kernel: [   50.734076] audit: type=1400 audit(1504241034.228:44): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6" pid=1534 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:54 localhost kernel: [   50.752876] audit: type=1400 audit(1504241034.248:45): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6" pid=1535 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:59 localhost kernel: [   55.734255] audit: type=1400 audit(1504241039.228:46): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6-0" pid=1536 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:59 localhost kernel: [   55.753301] audit: type=1400 audit(1504241039.248:47): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6-0" pid=1537 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:59 localhost kernel: [   55.772021] audit: type=1400 audit(1504241039.268:48): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6" pid=1538 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep  1 04:43:59 localhost kernel: [   55.790740] audit: type=1400 audit(1504241039.288:49): apparmor="DENIED" operation="mknod" profile="snap.mir-kiosk-apps.mir-kiosk-app-daemon" name="/dev/shm/lttng-ust-wait-6" pid=1539 comm="photoviewer" requested_mask="c" denied_mask="c" fsuid=0 oui

**Comment by gerboland** [comment]
Hi,
thanks for the report. Those reports you've supplied don't help much unfortunately

Those errors about lttng-ust-wait-6 are harmless and can be ignored. Giving us the output of 

`sudo journalctl -t mir-kiosk.mir-kiosk`

might give us more of a clue. 
Thanks
-G

**Comment by laxman456** [comment]
Hi gerboland,
No log entries with above command

$sudo journalctl -t mir-kiosk.mir-kiosk
-- No entries --

Regards,
Laxman

**Comment by AlanGriffiths** [comment]
Closing. Old, and not enough information to reproduce nor fix
