### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by indisoluble** [MirServer/mir-kiosk#14]
Hi all,

We are working in our company to develop an app with an UI and based on Ubuntu Core. With this objective, we started by following the steps described in https://tutorials.ubuntu.com/tutorial/x11-kiosk. This tutorial instructs us to install this snap however we noticed that there is no license which, by omission, makes this software proprietary.

We were wondering if you could add a license. MIT, Apache2 or similar would be great but, of course, that is your choice.

Regards.

**Comment by AlanGriffiths** [comment]
The principal software in this snap is from the Mir project. That is licensed GPL-3.0-only OR GPL-2.0-only. This is reflected on [the snapcraft page](https://snapcraft.io/mir-kiosk). Does that address your concerns?
