### ISSUE TITLE
mir-kiosk not starting on a Raspberry Pi 3 running Core 18

### ISSUE THREAD

**Issue by ed10vi** [MirServer/mir-kiosk#17]
The server does not start at boot
The journalctl output is:
`mirserver: Starting`

If I do an stop-start works fine

**Comment by liqdfire** [comment]
set the vt config item of the snap to 1
`snap set mir-kiosk vt=1`

**Comment by AlanGriffiths** [comment]
Same issue as https://github.com/MirServer/mir/issues/779

Sorry, I missed this report - it should be fixed by #26 (which has landed and should be on candidate and edge as soon as they have built ~30min.).

**Comment by AlanGriffiths** [comment]
Fixed by #26
