### ISSUE TITLE
Apparmor denial preventing app rendering

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir-kiosk#2]
I'm using Edge mir-libs and mir-kiosk snaps.

Installing mir-kiosk-apps, I see nothing rendering for the photoviewer. Digging I found this app armor denial prevents the app creating a surface in mir:

Log: apparmor="DENIED" operation="file_receive" profile="snap.mir-kiosk.mir-kiosk" pid=4710 comm=52504320546872656164 family="unix" sock_type="seqpacket" protocol=0 requested_mask="send receive" denied_mask="send receive" addr=none peer_addr=none peer="snap.mir-kiosk-apps.mir-kiosk-app-daemon"

snappy-debug.security scanlog had no suggestions. If I reinstall the mir-kiosk snap with --devmode, then I see rendered stuff.

**Comment by Saviq** [comment]
Please post your `snap interfaces`, `snap version` and `snap list`.

**Comment by gerboland** [comment]
https://pastebin.ubuntu.com/25520916/

**Comment by gerboland** [comment]
Hmm, after reboot, I cannot reproduce
