### ISSUE TITLE
Mouse offset from image on Raspberry Pi 3 with Ubuntu Core 18

### ISSUE THREAD

**Issue by jeppe-style** [MirServer/mir-kiosk#23]
When running on a Raspberry Pi 3 (Ubuntu Core 18) the mouse is offset from the image, meaning that the lower and right part of the screen is not reachable as well as the mouse pointer being offset from the image that is displayed. For instance if you try to click on a link/button you have to offset (left and above) the mouse from the element.

Running the same setup on an Intel NUC had no issues.

**Comment by AlanGriffiths** [comment]
Confirmed. (And does indeed seem specific to RPi3/core18.)

This workaround works for me:
```
snap set mir-kiosk cursor=software
```

**Comment by jeppe-style** [comment]
Thanks @AlanGriffiths! I can confirm that the workaround works for me too.

**Comment by Saviq** [comment]
We believe Core 20 and later has this fixed.
