### ISSUE TITLE
mir-kiosk should expose administrative applications in the snap 

### ISSUE THREAD

**Issue by ogra1** [MirServer/mir-kiosk#3]
when trying to run mir-kiosk on a raspberry pi with a rotated monitor attached i can not use:

"mirout rotate right"

because the app is not exposed via snapcraft.yaml (even though mirout, mirscreencast and friends are existing in $SNAP/usr/bin), please add an apps section with commonly used mir administration tools to the mir-kiosk snap so they can be used by a user through /snap/bin.

**Comment by ogra1** [comment]
specifically for the rotation bit a config option via "snap set mir-kiosk rotation=*" might also be helpful

**Comment by gerboland** [comment]
That's a good idea indeed

**Comment by AlanGriffiths** [comment]
See also https://forum.snapcraft.io/t/invoke-configure-hook-from-other-snap/13755

**Comment by Saviq** [comment]
This is now reworked in Frame:

https://mir-server.io/docs/how-to-configure-ubuntu-frame-for-multiple-outputs
