### ISSUE TITLE
Raspberry Pi and hidecursor=true

### ISSUE THREAD

**Issue by gelinger777** [MirServer/mir-kiosk#30]
Hi There ! Mir Kiosk installed on Raspberry PI3 with hidecursor=true and the mouse pointer is still there ...

**Comment by wmww** [comment]
First of all, I believe the correct incantation is `snap set mir-kiosk cursor=none`. As far as I can tell, `hidecursor` isn't an option (not sure why setting it doesn't throw an error). `cursor=none` does set the cursor option to `null` in `/var/snap/mir-kiosk/current/miral-kiosk.config`, but the config file doesn't seem to be getting picked up by Mir Kiosk (at least on my machine). You can try running Mir Kiosk with `--cursor=null`

**Comment by AlanGriffiths** [comment]
@wmww that config should be picked up by the daemon, but will be missed if run as a normal user.

That's an issue, but I think you've anwered the OP already.

**Comment by AlanGriffiths** [comment]
@wmww 

>  (not sure why setting it doesn't throw an error)

https://forum.snapcraft.io/t/verifying-snap-configuration-keys-and-issuing-warnings/13497

**Comment by gelinger777** [comment]
Sorry but we decided to go on with FullPageOS for now, but I will look back when you have more stable configs. Plus there were huge problem to set the Resolution thing with MIR. It was not detecting the proper resolution of my  HDMI  hd monitor, and I had absolute no mood to dig into the config.
