### ISSUE TITLE
Add socket-activation to mir-kiosk

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir-kiosk#33]
Otherwise we run a risk of the client trying to connect to a non-existant socket.

Documentation:
https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html
http://0pointer.de/blog/projects/socket-activation.html

Support in snapd: https://github.com/snapcore/snapd/pull/3916

**Comment by AlanGriffiths** [comment]
> Let's see what comes out of https://forum.snapcraft.io/t/socket-activation-for-well-known-locations/7544

@Saviq this now looks like a dead end. Any need to keep this open?

**Comment by Saviq** [comment]
@AlanGriffiths going for a user session makes more sense indeed. And for Mir to auto-launch apps as configured.
