### ISSUE TITLE
mir-kiosk clashes with tty1 

### ISSUE THREAD

**Issue by popey** [MirServer/mir-kiosk#4]
I have "installed" Ubuntu Core on a Thinkpad T43. By "installed" I mean, I dd'ed the core image over the internal hard disk, booted up and went through the setup. I installed mir-kiosk and mir-kiosk-apps from the beta channel while logged in to the machine directly on tty1. The mir kiosk fails to launch. However I am able to start it when ssh'ed in (and not logged in on a tty). I get a black screen with mouse cursor.

**Comment by AlanGriffiths** [comment]
Fixed by https://github.com/MirServer/mir-kiosk/commit/6ad04b56112a9bc5e9e10943df9f43cac40d54a9
