### ISSUE TITLE
`configure` hook accepts empty values

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir-kiosk#42]
```bash
 snap set mir-kiosk vt=                            
 snap set mir-kiosk daemon=
 snap set mir-kiosk cursor=
 snap get mir-kiosk                                
Key             Value
cursor          
daemon          
display-layout  default
show-splash     
vt              
 cat /var/snap/mir-kiosk/current/miral-kiosk.config
arw-file=
console-provider=vt
env-hacks=MIR_MESA_KMS_DISABLE_MODESET_PROBE
display-layout=default
vt=4
cursor=auto
show-splash=false
```

**Comment by AlanGriffiths** [comment]
Yes, there are various problems with the current approach to configuration. Another is that we can't easily tell if configuration options are misspelt.

I think we should change tack and use something more like our `display-config` option to set the .config contents. But we also need some sort of "validate config" utility to parse these files.
