### ISSUE TITLE
Is there a way to modify the double-click time on touchscreens?

### ISSUE THREAD

**Issue by ZaneL** [MirServer/mir-kiosk#51]
When I click on buttons it often seems like my touch screen is generating two clicks rather than one.  Is there a way to disable double clicking, or at least a way to define a minimum time period in between clicks?

**Comment by wmww** [comment]
That sounds like it might be a bug in our touch logic. Could you run an app with `WAYLAND_DEBUG=client` set and capture the log printed to stderr?

EDIT: also, what app did you observe this with? Have you seen the same behavior with multiple apps that use multiple toolkits? Are there other Wayland compositors or desktops in general for which this isn't an issue? What hardware are you running on?

**Comment by ZaneL** [comment]
```
me@linux:/lib/udev/hwdb.d$ snap logs mir-kiosk
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.602978] <information> mirserver: . |_ Physical size 0.0" 0x0mm
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603023] <information> mirserver: . |_ Power is on
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603075] <information> mirserver: . |_ Current mode 800x480 62.09Hz
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603123] <information> mirserver: . |_ Preferred mode 800x480 62.09Hz
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603168] <information> mirserver: . |_ Orientation left
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603223] <information> mirserver: . |_ Logical size 480x800
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603268] <information> mirserver: . |_ Logical position +0+0
2020-12-16T03:15:27Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:27.603314] <information> mirserver: . |_ Scaling factor: 1.00
2020-12-16T03:15:29Z mir-kiosk.daemon[12421]: [2020-12-16 03:15:29.770182] < - debug - > wayland-gfx-helpers: Wayland buffer destroyed before use; rendering will be incomplete
2020-12-16T03:16:52Z mir-kiosk.daemon[12421]: [2020-12-16 03:16:52.422683] <information> evdev-input: Added /dev/input/event0
```

This is the output after booting up the mir-kiosk snap and clicking on the touch screen. When I keep clicking on stuff it doesn't generate any more output to the logs. Essentially what is happening is I'm running a web-based kiosk running on top of mir-kiosk and there is some weird "glitch" that occurs when I click on the buttons. With the CSS ripple effect buttons tend to "ripple" multiple times, even when I click on them one time. I can't quite figure out if it's a graphics rendering issue or an input issue. This whole stack is running on a raspberry pi 3.

I haven't had time to test it on other systems, but I will soon.

**Comment by ZaneL** [comment]
me@linux:/lib/udev/hwdb.d$ sudo cat /dev/input/event0
▒▒_▒H9▒▒_▒H5▒▒_▒H6▒▒▒_▒H0▒▒_▒H2▒▒_▒HJ▒▒_▒H▒▒_▒H▒▒▒_▒H▒▒_?9▒▒▒▒▒▒_?J▒▒_?
me@linux:/lib/udev/hwdb.d$ sudo cat /dev/input/event0
▒▒_▒▒9▒▒▒▒▒▒_▒▒J▒▒_▒▒
me@linux:/lib/udev/hwdb.d$ sudo cat /dev/input/event0
▒▒_9!▒▒_5▒▒_6{▒▒_J▒▒_▒▒_{▒▒_▒▒_▒h       9▒▒▒▒▒▒_▒h      J▒▒_▒h  
me@linux:/lib/udev/hwdb.d$ sudo cat /dev/input/event0
▒▒_Đ^C▒▒▒
me@linux:/lib/udev/hwdb.d$ sudo cat /dev/input/event0
▒▒_R09#▒▒_R05▒▒_R06▒▒▒_R00▒▒_R02▒▒_R0J▒▒_R0▒▒_R0▒▒▒_R0▒▒_▒9▒▒▒▒▒▒_▒J▒▒_▒

Here is the output coming off of the touchscreen when I click once in roughly the same location 5x. I wonder if there is a way to convert this raw data into a string that can be read? I can't tell if the driver is sometimes generating multiple clicks, but it looks like it might be?

**Comment by wmww** [comment]
When you say a "web-based kiosk", I'm guessing that's Chromium running on XWayland?

You should be able to figure out if multiple clicks are actually being recorded with something like this: https://tallycounterstore.com/online-counter

Does the ripple happen constantly, whenever the touch moves, once on press and once on release or something else?

**Comment by wmww** [comment]
If you can run Mir with `WAYLAND_DEBUG=server` set, the logs will become a lot more useful to me.

**Comment by ZaneL** [comment]
This:
[https://snapcraft.io/wpe-webkit-mir-kiosk](https://snapcraft.io/wpe-webkit-mir-kiosk)

Okay I set the environmental variable outside of the snap and within the snap and rebooted and it doesn't seem to change anything when looking at "snap logs mir-kiosk". Maybe I'm doing something wrong...

```
me@linux:/lib/udev/hwdb.d$ snap run --shell mir-kiosk
me@linux:/lib/udev/hwdb.d$ export WAYLAND_DEBUG=server
me@linux:/lib/udev/hwdb.d$ exit
me@linux:/lib/udev/hwdb.d$ export WAYLAND_DEBUG=server
me@linux:/lib/udev/hwdb.d$ snap restart mir-kiosk
```

**Comment by ZaneL** [comment]
I think it might be related to this.

[https://bugzilla.kernel.org/show_bug.cgi?id=106461](https://bugzilla.kernel.org/show_bug.cgi?id=106461)

Later this week I'll try to build a modified touch driver and see if that fixes it.

**Comment by wmww** [comment]
@AlanGriffiths might know how to set the environment variable when he comes online. That bug looks like it very well might be relevant. You could probably hack Mir to work around that issue, but building a working driver is probs easier.

**Comment by AlanGriffiths** [comment]
You're running Ubuntu Core 18 on the RPi3? So these snaps are started as daemons?

Rebooting after setting environment variables is (obviously) going to lose those settings. Also, I'm not sure what you mean by "set the environmental variable ... within the snap"? You modified the snap? You changed the systemd config?

In any case, it is possible to use the `env-hacks` Mir configuration option to adjust the environment in the mir-kiosk snap. Essentially, you need to create a config file with a line `env-hacks=WAYLAND_DEBUG=server` and then `snap restart mir-kiosk` (see ["Configuring mir-kiosk: a masterclass"](https://discourse.ubuntu.com/t/configuring-mir-kiosk-a-masterclass/8150) for details).

I'd be surprised if Mir is the source of "double touch". The touchscreen on my (old) laptop died a few weeks ago so I can't test touch things at the moment, but we've not needed to change that code for a long time.

**Comment by ZaneL** [comment]
Sorry, this is definitely a graphical issue and not a touch issue. I think my PI is just a little slow so it has trouble rendering web animations.
