### ISSUE TITLE
Proposal can we work on using: Chromium?

### ISSUE THREAD

**Issue by frank-dspeed** [MirServer/mir-kiosk#65]
Chromium has wayland support but i am not so familar with ubuntu frame and cross snap things

but i guess you can get it running via

```
chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
```
i am not sure what is missing to get that working but in general chromium supports that

also a fix has landed to support direct wayland exposing via the snap

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1897454

the current chromium snap contains that

**Comment by AlanGriffiths** [comment]
Yes, you can use chromium's Wayland support with mir-kiosk

**Comment by frank-dspeed** [comment]
@AlanGriffiths how does that work do you got any example? i tought mir kiosk does implement its own browser?

**Comment by AlanGriffiths** [comment]
It should work the same as with Frame: https://github.com/MirServer/mir/issues/2463#issuecomment-1152185260
